DROP TABLE TEMP_RS_32543453452343

CREATE TABLE TEMP_RS_32543453452343 NOLOGGING PARALLEL AS 
SELECT /*+ INDEX(T3) */ 
RECORD_TYPE,BS_GL,( SELECT GL_DESCRIPTION FROM GL_CODES WHERE COUNTRY='VN' AND VISION_GL= BS_GL ) GL_DESCRIPTION,
CUSTOMER_ID ,CONTRACT_ID ,COST_CENTER,
  T2.BAL_TYPE,
  MIS_CURRENCY,
         SUM (BALANCE_01 ) NGAY1,
         SUM (BALANCE_02 ) NGAY2,
         SUM (BALANCE_03 ) NGAY3,
         SUM (BALANCE_04 ) NGAY4,
         SUM (BALANCE_05 ) NGAY5,
         SUM (BALANCE_06 ) NGAY6,
         SUM (BALANCE_07 ) NGAY7,
         SUM (BALANCE_08 ) NGAY8,
         SUM (BALANCE_09 ) NGAY9,
         SUM (BALANCE_10 ) NGAY10,
         SUM (BALANCE_11 ) NGAY11,
         SUM (BALANCE_12 ) NGAY12,
         SUM (BALANCE_13 ) NGAY13,
         SUM (BALANCE_14 ) NGAY14,
         SUM (BALANCE_15 ) NGAY15,
         SUM (BALANCE_16 ) NGAY16,
         SUM (BALANCE_17 ) NGAY17,
         SUM (BALANCE_18 ) NGAY18,
         SUM (BALANCE_19 ) NGAY19,
         SUM (BALANCE_20 ) NGAY20,
         SUM (BALANCE_21 ) NGAY21,
         SUM (BALANCE_22 ) NGAY22,
         SUM (BALANCE_23 ) NGAY23,
         SUM (BALANCE_24 ) NGAY24,
         SUM (BALANCE_25 ) NGAY25,
         SUM (BALANCE_26 ) NGAY26,
         SUM (BALANCE_27 ) NGAY27,
         SUM (BALANCE_28 ) NGAY28,
         SUM (BALANCE_29 ) NGAY29,
         SUM (BALANCE_30 ) NGAY30,
         SUM (BALANCE_31 ) NGAY31
FROM VW_FIN_DLY_HEADERS T1, FIN_DLY_BALANCES T2 
WHERE     T1.COUNTRY = T2.COUNTRY
     AND T1.LE_BOOK = T2.LE_BOOK
     AND T1.YEAR_MONTH = T2.YEAR_MONTH
     AND T1.SEQUENCE_FD = T2.SEQUENCE_FD 
     AND T1.COUNTRY = 'VN'
     AND T1.LE_BOOK = '01'
     AND T1.YEAR_MONTH = '202007'
     AND T1.RECORD_TYPE   <>9999
     AND T2.BAL_TYPE    IN (57,58) 
     AND RECORD_TYPE<>22
     AND EXISTS (
     SELECT 1 FROM PWT_FI_FUND_VW A
     WHERE T1.CONTRACT_ID =A.CONTRACT_ID  )
     AND SUBSTR(BS_GL,1,1) ='1'
     GROUP BY -- CUSTOMER_ID,CONTRACT_ID,  
RECORD_TYPE,BS_GL,  CUSTOMER_ID ,CONTRACT_ID ,T2.BAL_TYPE,MIS_CURRENCY,COST_CENTER
 

 