CREATE OR REPLACE PROCEDURE VISION.FTP_TAB (BUSINESS_DATE IN DATE)
IS
   P_STATUS     VARCHAR2 (32767);
   P_ERRORMSG   VARCHAR2 (32767);
   YEARMONTH    VARCHAR2 (32767);
   BDAY         VARCHAR2 (32767);
   RWCNT        NUMBER;
BEGIN
   EXECUTE IMMEDIATE
      'SELECT to_char(trunc(max(sysdate),''MM'')   ,''RRRRMM'') FROM dual'
      INTO YEARMONTH;

   EXECUTE IMMEDIATE 'SELECT (trunc(max(sysdate),''MM'') ) FROM dual'
      INTO BDAY; 
 
   EXECUTE IMMEDIATE
         'CREATE OR REPLACE VIEW   TEMP_RS_324234523423 AS 
        SELECT /*+PARALLEL(3)*/ distinct  * FROM  
        (SELECT 
         DISTINCT COUNTRY, LE_BOOK, CUSTOMER_ID, CONTRACT_ID,CONTRACT_SEQUENCE_NUMBER,
          SOURCE_ID, VISION_OUC, VISION_SBU, ACCOUNT_OFFICER, DEAL_TYPE, DEAL_SUB_TYPE, START_DATE, MATURITY_DATE, 
          CONTRACT_STATUS, PRINCIPAL_GL, PRINCIPAL_AMOUNT, MIS_CURRENCY, INTEREST_RATE,DATE_LAST_MODIFIED, DATE_CREATION,
         ROW_NUMBER () OVER ( PARTITION BY  CUSTOMER_ID, CONTRACT_ID
          ORDER BY CONTRACT_SEQUENCE_NUMBER DESC, MATURITY_DATE DESC,CONTRACT_STATUS,INTEREST_RATE DESC) RN FROM 
        (SELECT DISTINCT CONTRACT_SEQUENCE_NUMBER, COUNTRY, LE_BOOK, CUSTOMER_ID, CONTRACT_ID, RECORD_TYPE_NT, RECORD_TYPE, SOURCE_ID_NT,
            SOURCE_ID, VISION_OUC, VISION_SBU_AT, VISION_SBU, ACCOUNT_OFFICER, ISSUE_ID, DEAL_TYPE, DEAL_SUB_TYPE, START_DATE, MATURITY_DATE, SETTLEMENT_DATE, 
            DAYS_REMAINING_MAT, DAYS_START_MAT, ACCRUAL_STATUS_NT, ACCRUAL_STATUS, CONTRACT_STATUS_NT, CONTRACT_STATUS, PRINCIPAL_GL, PRINCIPAL_AMOUNT, MIS_CURRENCY, 
            POOL_CODE, INTEREST_RATE, COST_OF_FUNDS_RATE, GL_ENRICH_ID, DATE_LAST_MODIFIED, DATE_CREATION, STATUS_NT, STATUS FROM CONTRACTS A
        WHERE COUNTRY=''VN'' AND LE_BOOK=''01'' AND SOURCE_ID=6
        AND '
      || YEARMONTH
      || ' BETWEEN TO_CHAR(TO_DATE(START_DATE),''RRRRMM'') AND TO_CHAR(TO_DATE(MATURITY_DATE),''RRRRMM'')
        UNION ALL
        SELECT DISTINCT CONTRACT_SEQUENCE_NUMBER, COUNTRY, LE_BOOK, CUSTOMER_ID, CONTRACT_ID, RECORD_TYPE_NT, RECORD_TYPE, SOURCE_ID_NT, 
            SOURCE_ID, VISION_OUC, VISION_SBU_AT, VISION_SBU, ACCOUNT_OFFICER, ISSUE_ID, DEAL_TYPE, DEAL_SUB_TYPE, START_DATE, MATURITY_DATE, SETTLEMENT_DATE, 
            DAYS_REMAINING_MAT, DAYS_START_MAT, ACCRUAL_STATUS_NT, ACCRUAL_STATUS, CONTRACT_STATUS_NT, CONTRACT_STATUS, PRINCIPAL_GL, PRINCIPAL_AMOUNT, MIS_CURRENCY, 
            POOL_CODE, INTEREST_RATE, COST_OF_FUNDS_RATE, GL_ENRICH_ID, DATE_LAST_MODIFIED, DATE_CREATION, STATUS_NT, STATUS
        FROM CONTRACTS_HISTORY B
        WHERE COUNTRY=''VN'' AND LE_BOOK=''01'' AND SOURCE_ID=6
        AND '
      || YEARMONTH
      || ' BETWEEN TO_CHAR(TO_DATE(START_DATE),''RRRRMM'') AND TO_CHAR(TO_DATE(MATURITY_DATE),''RRRRMM'') 
        UNION ALL
        SELECT DISTINCT CONTRACT_SEQUENCE_NUMBER, COUNTRY, LE_BOOK, CUSTOMER_ID, CONTRACT_ID, RECORD_TYPE_NT, RECORD_TYPE, SOURCE_ID_NT, 
            SOURCE_ID, VISION_OUC, VISION_SBU_AT, VISION_SBU, ACCOUNT_OFFICER, ISSUE_ID, DEAL_TYPE, DEAL_SUB_TYPE, START_DATE, MATURITY_DATE, SETTLEMENT_DATE, 
            DAYS_REMAINING_MAT, DAYS_START_MAT, ACCRUAL_STATUS_NT, ACCRUAL_STATUS, CONTRACT_STATUS_NT, CONTRACT_STATUS, PRINCIPAL_GL, PRINCIPAL_AMOUNT, MIS_CURRENCY, 
            POOL_CODE, INTEREST_RATE, COST_OF_FUNDS_RATE, GL_ENRICH_ID, DATE_LAST_MODIFIED, DATE_CREATION, STATUS_NT, STATUS
        FROM ACCOUNT_CONFIDENTIAL_NAMES_PEND B
        WHERE COUNTRY=''VN'' AND LE_BOOK=''01'' AND SOURCE_ID=6
        AND '
      || YEARMONTH
      || ' BETWEEN TO_CHAR(TO_DATE(AUDIT_START_DATE),''RRRRMM'') AND TO_CHAR(TO_DATE(AUDIT_END_DATE),''RRRRMM'')))
        WHERE PRINCIPAL_AMOUNT!=0
        AND RN=1';

   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE VW_CONT_EXPANDED2 PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   EXECUTE IMMEDIATE
      'CREATE TABLE VW_CONT_EXPANDED2     AS  
        SELECT /*+PARALLEL(3)*/ DISTINCT  
        T5.CONTRACT_SEQUENCE_NUMBER, T5.COUNTRY, T5.LE_BOOK, T5.CUSTOMER_ID,
         T5.CONTRACT_ID, T5.SOURCE_ID, T5.VISION_OUC, T5.VISION_SBU, T5.ACCOUNT_OFFICER, 
        T5.DEAL_TYPE, T5.DEAL_SUB_TYPE, 
        T5.START_DATE, T5.MATURITY_DATE, T5.DAYS_REMAINING_MAT, T5.DAYS_START_MAT, T5.CONTRACT_STATUS, 
        T5.PRINCIPAL_GL, T5.PRINCIPAL_AMOUNT, T5.MIS_CURRENCY, 
        NVL(T6.INTEREST_RATE,T5.INTEREST_RATE)INTEREST_RATE, 
        LCY_EQUIV_INCEPTION, EXCHANGE_RATE, OPTION_EXERCISE_DATE, 
        FUTURES_MARKET_PRICE, FUTURES_COST_PRICE, FUT_VAR_MARGIN, REPRICING_DATE, INTREST_RATE, END_DATE, 
        REPRICING_TERM, REPRICING_TERM_CODE, NOMINAL_REPRICING_DATE, PARTID, LESRCF, LETYPF
        FROM (SELECT  T1.CONTRACT_SEQUENCE_NUMBER, T1.COUNTRY, T1.LE_BOOK, T1.CUSTOMER_ID,
        T1.CONTRACT_ID, T1.SOURCE_ID, T1.VISION_OUC, T1.VISION_SBU, T1.ACCOUNT_OFFICER, 
        T1.DEAL_TYPE, T1.DEAL_SUB_TYPE, 
        T1.START_DATE, T1.MATURITY_DATE, T1.DAYS_REMAINING_MAT, T1.DAYS_START_MAT, T1.CONTRACT_STATUS, 
        T1.PRINCIPAL_GL, T1.PRINCIPAL_AMOUNT, T1.MIS_CURRENCY, 
        T1.INTEREST_RATE INTEREST_RATE, 
        LCY_EQUIV_INCEPTION, EXCHANGE_RATE, OPTION_EXERCISE_DATE, 
        FUTURES_MARKET_PRICE, FUTURES_COST_PRICE, FUT_VAR_MARGIN, REPRICING_DATE, INTREST_RATE, END_DATE, 
        REPRICING_TERM, REPRICING_TERM_CODE, NOMINAL_REPRICING_DATE, PARTID, LESRCF, LETYPF
          FROM CONTRACTS T1, CONTRACT_EXTRAS T2
         WHERE T1.CONTRACT_SEQUENCE_NUMBER = T2.CONTRACT_SEQUENCE_NUMBER) T5,TEMP_RS_324234523423 T6
                WHERE  T5.COUNTRY = T6.COUNTRY(+)
                AND T5.LE_BOOK = T6.LE_BOOK(+)
                AND T5.CUSTOMER_ID = T6.CUSTOMER_ID(+)
                AND T5.CONTRACT_ID = T6.CONTRACT_ID(+)
                AND T5.SOURCE_ID = T6.SOURCE_ID(+)  ';

   DBMS_MVIEW.REFRESH ('VW_CURRENCY_RATES');


   --   BEGIN
   --      EXECUTE IMMEDIATE 'TRUNCATE TABLE VW_CONT_EXPANDED1';
   --   EXCEPTION
   --      WHEN OTHERS
   --      THEN
   --         IF SQLCODE != -0942A
   --         THEN
   --            DBMS_OUTPUT.PUT_LINE ('#$%^');
   --         END IF;
   --   END;
   --
   --   DBMS_MVIEW.REFRESH ('VW_CONT_EXPANDED1');

   --   DBMS_OUTPUT.PUT_LINE ('++++++++' || YEARMONTH);

   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS_FTP PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('#$%^');
         END IF;
   END;



   BEGIN
      EXECUTE IMMEDIATE
         'CREATE TABLE     CUSTOMERS_FTP           AS 
    SELECT DISTINCT CUSTOMER_ID ,CUSTOMER_NAME FROM CUSTOMERS_DLY';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE 'CREATE INDEX CUSTFTO ON CUSTOMERS_FTP( CUSTOMER_ID)';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
         'DROP TABLE FIN_DLY_HEADERS_FTP_' || YEARMONTH || ' PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE           FIN_DLY_HEADERS_FTP_'
         || YEARMONTH
         || '        AS 
    SELECT  COUNTRY, LE_BOOK, YEAR_MONTH, SEQUENCE_FD,
    T2.CUSTOMER_ID,
    T2.CONTRACT_ID, 
    T2.OFFICE_ACCOUNT,
    T2.GL_ENRICH_ID,
    T2.BS_GL,
    T2.PL_GL,
    T2.VISION_OUC,
    T2.VISION_SBU,
    T2.ACCOUNT_OFFICER,
    T2.COST_CENTER,
    T2.CURRENCY, 
    T2.MIS_CURRENCY,
    T2.ACCRUAL_STATUS,
    T2.CREDIT_LINE,
    T2.POOL_CODE,
    T2.SOURCE_ID,
    T2.ORIGINAL_OUC,
    T2.RECORD_TYPE FROM VW_FIN_DLY_HEADERS T2 WHERE
    COUNTRY=''VN'' AND LE_BOOK=''01'' AND YEAR_MONTH='
         || YEARMONTH
         || ' AND PL_GL=0 AND RECORD_TYPE<>9999';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE BITMAP INDEX FIN_DLY_HEADERS_FTP_'
         || YEARMONTH
         || '_PK ON VISION.FIN_DLY_HEADERS_FTP_'
         || YEARMONTH
         || '
    (COUNTRY, LE_BOOK, YEAR_MONTH, SEQUENCE_FD)';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE FTP_AUDIT_' || YEARMONTH || ' PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE   FTP_AUDIT_'
         || YEARMONTH
         || '            AS 
    SELECT * FROM FTP_AUDIT WHERE COUNTRY=''VN'' AND LE_BOOK=''01'' AND YEAR_MONTH='
         || YEARMONTH
         || '';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;


   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE FTP_AUDIT_' || YEARMONTH || '_RW PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;


   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE FTP_AUDIT_'
         || YEARMONTH
         || '_RW             AS  
    SELECT COUNTRY, 
    LE_BOOK, 
    YEAR_MONTH, 
    BUSINESS_DATE, 
    NVL(T12.SEQUENCE_FD_NEW, T12.SEQUENCE_FD) SEQUENCE_FD,  
    MAX(VERSION_NO) VERSION_NO ,
    MAX(ROWID) KEEP(DENSE_RANK FIRST ORDER BY VERSION_NO DESC NULLS LAST) RW 
    FROM FTP_AUDIT_'
         || YEARMONTH
         || ' T12 
    WHERE ''VN'' = COUNTRY 
    AND ''01'' = LE_BOOK 
    AND '
         || YEARMONTH
         || ' = YEAR_MONTH   
    GROUP BY COUNTRY, LE_BOOK, YEAR_MONTH, BUSINESS_DATE, NVL(T12.SEQUENCE_FD_NEW, T12.SEQUENCE_FD)';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE TEMPF_CONTRACTS_HISTORY PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE TEMPF_CONTRACTS_HISTORY    AS
    SELECT /*+PARALLEL(3)*/ * FROM (    
SELECT CUSTHIS.*,ROW_NUMBER () OVER ( PARTITION BY CUSTOMER_ID, CONTRACT_ID
     ORDER BY AUDIT_START_DATE , AUDIT_END_DATE , CUSTOMER_ID, CONTRACT_ID ) DUP
    FROM CONTRACTS_HISTORY CUSTHIS WHERE AUDIT_END_DATE>=TRUNC(TO_DATE('''|| BDAY|| '''),''MM'') )
    WHERE DUP=1 ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
         'CREATE INDEX TEMPF_CONTRACTS_HISTORYIDF ON TEMPF_CONTRACTS_HISTORY (CONTRACT_SEQUENCE_NUMBER,AUDIT_START_DATE,AUDIT_END_DATE)';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
         'DROP TABLE AUTO_FTP_AUDIT_TAB_' || YEARMONTH || ' PURGE ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE    AUTO_FTP_AUDIT_TAB_'
         || YEARMONTH
         || '           
                    TABLESPACE VISION_DATA_FTP_AUDIT    AS   
    SELECT DISTINCT
    T1.YEAR_MONTH,
    T1.BUSINESS_DATE,
    NVL(T2.VISION_SBU,T1.VISION_SBU) VISION_SBU,
    T2.CUSTOMER_ID,
    T2.CONTRACT_ID,
    T3.CUSTOMER_NAME,
    T2.CURRENCY,
    T4.RATE EXCHANGE_RATE,
    T2.MIS_CURRENCY,
    T1.FTP_GROUP,
    T1.FTP_REFERENCE,
    T1.FTP_SOURCE_REFERENCE,
    T1.FTP_METHOD_REFERENCE,
    T1.METHOD_TYPE,
    T1.REPRICING_FLAG,
    T1.FTP_TENOR_TYPE,
    T1.LP_TENOR_TYPE,             
    NVL (G.START_DATE, T5.START_DATE) START_DATE,
    NVL (G.MATURITY_DATE, T5.MATURITY_DATE) MATURITY_DATE,
    T1.START_REPRICE_DATE,
    T1.NEXT_REPRICE_DATE,
    NVL (T5.REPRICING_TERM, ''NA'') REPRICING_TERM,
    NVL (T5.REPRICING_TERM_CODE, ''NA'') REPRICING_TERM_CODE,
    T1.BALANCE,
    (NVL(T1.FTP * T4.RATE,0))+
    (NVL(T1.FTP_ADJUSTMENT * T4.RATE,0)) +
    (NVL(T1.PREMIUM * T4.RATE,0)) +
    (NVL(T1.REQUIRED_RESERVE_AMT * T4.RATE,0)) +
    (NVL(T1.GL_ALLOCATION_AMT * T4.RATE,0)) +
    (NVL(T1.ADDON_DEPOSIT_AMT * T4.RATE,0)) +
    (NVL(T1.ADDON_LENDING_AMT * T4.RATE,0)) +
    (NVL(T1.ADDON_ATT_AMT1 * T4.RATE,0)) +
    (NVL(T1.SUBSIDY_AMT * T4.RATE,0)) FTP_TOTAL,  
    (NVL(T1.FTP_CURVE+T1.FTP_ADDON+T1.FTP_SUBSIDY+T1.ADDON_DEPOSIT_RATE+T1.SUBSIDY_RATE+ 
    T1.ADDON_LENDING_RATE+T1.REQUIRED_RESERVE_RATE+ T1.GL_ALLOCATION_RATE+T1.ADDON_ATT_RATE1+T1.LP_RATE,0)) FTP_RATE_TOTAL,
    (CASE WHEN T2.SOURCE_ID =6 THEN CASE WHEN T5.INTEREST_RATE < 1 THEN T5.INTEREST_RATE*100  ELSE  T5.INTEREST_RATE END
     ELSE
     ROUND( NVL(CASE WHEN G.INTEREST_RATE  < 1 THEN  G.INTEREST_RATE*100  ELSE  G.INTEREST_RATE END,
                CASE WHEN T5.INTEREST_RATE < 1 THEN T5.INTEREST_RATE*100  ELSE  T5.INTEREST_RATE END),5) END)
       CUSTOMER_INTEREST,
--    CASE WHEN FTP_GROUP IN (''LOAN'',''OVERD'',''CREDITCARD'',''CBI'') THEN 
--    (CASE WHEN NVL(T5.INTEREST_RATE,0)  < 1 THEN NVL(T5.INTEREST_RATE*100,0) ELSE NVL(T5.INTEREST_RATE,0) END) -
--    (NVL(T1.FTP_CURVE+T1.FTP_ADDON+T1.FTP_SUBSIDY+T1.ADDON_DEPOSIT_RATE+T1.SUBSIDY_RATE+ T1.ADDON_LENDING_RATE+T1.REQUIRED_RESERVE_RATE+
--    T1.GL_ALLOCATION_RATE+T1.ADDON_ATT_RATE1+T1.LP_RATE,0))
--    WHEN FTP_GROUP IN (''FD'',''CASA'') THEN 
--    (NVL(T1.FTP_CURVE+T1.FTP_ADDON+T1.FTP_SUBSIDY+T1.ADDON_DEPOSIT_RATE+T1.SUBSIDY_RATE+ T1.ADDON_LENDING_RATE+T1.REQUIRED_RESERVE_RATE+
--    T1.GL_ALLOCATION_RATE+T1.ADDON_ATT_RATE1+T1.LP_RATE,0))-
--     (CASE WHEN T2.SOURCE_ID =6 THEN CASE WHEN T5.INTEREST_RATE < 1 THEN T5.INTEREST_RATE*100  ELSE  T5.INTEREST_RATE END
--     ELSE
--     ROUND( NVL(CASE WHEN G.INTEREST_RATE  < 1 THEN  G.INTEREST_RATE*100  ELSE  G.INTEREST_RATE END,
--                CASE WHEN T5.INTEREST_RATE < 1 THEN T5.INTEREST_RATE*100  ELSE  T5.INTEREST_RATE END),5) END)
--    ELSE 
--    (( ROUND( NVL(CASE WHEN G.INTEREST_RATE  < 1 THEN  G.INTEREST_RATE*100  ELSE  G.INTEREST_RATE END,
--    CASE WHEN  T5.INTEREST_RATE   < 1 THEN  T5.INTEREST_RATE*100  ELSE  T5.INTEREST_RATE  END)  ,5) ) -
--    (NVL(T1.FTP_CURVE+T1.FTP_ADDON+T1.FTP_SUBSIDY+T1.ADDON_DEPOSIT_RATE+T1.SUBSIDY_RATE+ T1.ADDON_LENDING_RATE+T1.REQUIRED_RESERVE_RATE+
--    T1.GL_ALLOCATION_RATE+T1.ADDON_ATT_RATE1+T1.LP_RATE,0)))
--    END FTP_MARGIN,
    T1.FTP_CURVE_ID,
    T1.FTP_RATE_ID,
    T1.FTP_CURVE,
    T1.FTP_ADDON,
    T1.FTP_SUBSIDY,
    T1.LP_RATE_ID,
    T1.LP_RATE,       
    T1.FTP FTP_AMOUNT,
    T1.FTP_ADJUSTMENT,
    T1.PREMIUM,
    T1.ADDON_DEPOSIT_RATE,
    T1.ADDON_DEPOSIT_AMT,
    T1.SUBSIDY_RATE,
    T1.SUBSIDY_AMT,
    T1.ADDON_LENDING_RATE,
    T1.ADDON_LENDING_AMT,
    T1.REQUIRED_RESERVE_RATE,
    T1.REQUIRED_RESERVE_AMT,
    T1.GL_ALLOCATION_RATE,
    T1.GL_ALLOCATION_AMT,
    T1.ADDON_ATT_RATE1,
    T1.ADDON_ATT_AMT1,
    T2.OFFICE_ACCOUNT,
    T2.GL_ENRICH_ID,
    T2.BS_GL,
    T2.PL_GL,
    T2.VISION_OUC,
    T2.ACCOUNT_OFFICER,
    T2.COST_CENTER,
    LESRCF SOURCE_OF_FUND,
    T2.SOURCE_ID,
    T2.RECORD_TYPE,
    T2.ORIGINAL_OUC, 
    T1.DATE_LAST_MODIFIED,
    T1.DATE_CREATION, T1.COUNTRY,
    T1.LE_BOOK,
    T1.SEQUENCE_FD,
    T1.SEQUENCE_FD_NEW,
    T1.VERSION_NO,
    NVL(T1.VISION_SBU,T2.VISION_SBU) sbu_audit
    FROM FIN_DLY_HEADERS_FTP_'
         || YEARMONTH
         || ' T2,FTP_AUDIT_'
         || YEARMONTH
         || ' T1,  CUSTOMERS_FTP T3,
    VW_CURRENCY_RATES T4,
    TEMPF_CONTRACTS_HISTORY G,VW_CONT_EXPANDED2 T5 
    WHERE     T1.COUNTRY = ''VN''
    AND T1.LE_BOOK = ''01''
    AND T1.YEAR_MONTH = '
         || YEARMONTH
         || ' 
    AND T2.SEQUENCE_FD = NVL(T1.SEQUENCE_FD_NEW,T1.SEQUENCE_FD)
    AND T2.COUNTRY = T1.COUNTRY || ''''
    AND T2.LE_BOOK = T1.LE_BOOK
    AND T2.YEAR_MONTH = T1.YEAR_MONTH 
    AND T2.COUNTRY || '''' = ''VN''
    AND T2.LE_BOOK = ''01''
    AND T2.YEAR_MONTH = '
         || YEARMONTH
         || '
    AND EXISTS
    (SELECT 1
     FROM FTP_AUDIT_'
         || YEARMONTH
         || '_RW T11
    WHERE T1.ROWID = T11.RW)
    AND T2.CUSTOMER_ID = T3.CUSTOMER_ID (+)
    AND T4.COUNTRY = T1.COUNTRY
    AND T4.LE_BOOK = T1.LE_BOOK
    AND T4.BUSINESS_DAY = T1.BUSINESS_DATE
    AND T2.CURRENCY = T4.CURRENCY
    AND T2.COUNTRY = T5.COUNTRY(+)
    AND T2.LE_BOOK = T5.LE_BOOK(+)
    AND T2.CUSTOMER_ID = T5.CUSTOMER_ID(+)
    AND T2.CONTRACT_ID = T5.CONTRACT_ID(+)
    AND T2.SOURCE_ID = T5.SOURCE_ID(+) 
    AND T5.CONTRACT_SEQUENCE_NUMBER = G.CONTRACT_SEQUENCE_NUMBER(+)  
    AND BUSINESS_DATE BETWEEN G.AUDIT_START_DATE(+) AND G.AUDIT_END_DATE(+)  ';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++1');
         END IF;
   END;


   BEGIN
      EXECUTE IMMEDIATE
            'DELETE  FTP_VKONDOR WHERE DATE_TX='''
         || BDAY
         || '''
        AND PRODUCTCODE=''ECON_UNL''';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('#$%^');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE 'INSERT INTO FTP_VKONDOR
        SELECT /*+PARALLEL(3)*/
        TRUNC (DATE_TX)DATE_TX,
        MODULE,
        TABLEID,
        ORG_DEALTICKET,
        DEALTICKET,
        TRUNC(OPEN_DATE)OPEN_DATE,
        TRUNC (MAT_DATE)MAT_DATE,
        CBAL,
        LCY_CBAL,
        INTEREST,
        CURTYP,
        EXCH_RATE,
        TERMDAY,
        ACCTGL,
        ACCTGL_INT,
        ACCR,
        LCY_ACCR,
        LAI_DT_TRC_MUA_NT,
        LAI_DT_TRC_MUA_VND,
        PL_GL_INT,
        PENDINGCKPT,
        ACCTGL_CKPT,
        YIELD,
        TRUNC (LAST_COUPON_DT)LAST_COUPON_DT,
        PRODUCTCODE,
        KONDOR_FOLDERNAME,
        SONGAYCONLAI,
        CIFNO,
        CFINDI,
        TENKHACHHANG,
        ISSUER_NAME,
        ETL_DATE,
        STATUS
        FROM TEMP_VW_KONDOR
        WHERE PRODUCTCODE=''ECON_UNL''';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('#$%^');
         END IF;
   END;

   BEGIN
      EXECUTE IMMEDIATE ('TRUNCATE TABLE FTP_CBI');
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE = -30
         THEN
            NULL;
         END IF;
   END;
  

   BEGIN
      EXECUTE IMMEDIATE
            'CREATE TABLE  FTP_CBI     AS                  
        SELECT DISTINCT FTP.ROWID RWID,KPLUS.INTEREST 
            FROM AUTO_FTP_AUDIT_TAB_'|| YEARMONTH|| ' FTP ,PWT_VKONDOR_VW KPLUS
            WHERE FTP.CONTRACT_ID =TO_CHAR(KPLUS.ORG_DEALTICKET)
            AND REPLACE(FTP.CUSTOMER_ID,''FT000'','''')=TO_CHAR(KPLUS.CIFNO) 
            AND FTP.BUSINESS_DATE=KPLUS.DATE_TX
            AND FTP.FTP_GROUP IN (''CBI'',''FD'',''INTPAY'',''INTREC'')  ';

      DBMS_OUTPUT.PUT_LINE ('--10' || SYSTIMESTAMP);
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE = -30
         THEN
            NULL;
         END IF;
   END;


   COMMIT;

   DECLARE
      CURSOR EB
      IS
         SELECT * FROM FTP_CBI;
   BEGIN
      FOR I IN EB
      LOOP
         EXECUTE IMMEDIATE
               ' UPDATE AUTO_FTP_AUDIT_TAB_'
            || YEARMONTH
            || '
            SET CUSTOMER_INTEREST = '''|| I.INTEREST|| '''--, FTP_MARGIN = ABS('''|| I.INTEREST|| ''' - FTP_RATE_TOTAL) 
          WHERE ROWID  = '''
            || I.RWID
            || ''' ';

         RWCNT := RWCNT + 1;

         IF (MOD (RWCNT, 2000) = 0)
         THEN
            COMMIT;
         END IF;
      END LOOP;

      COMMIT;
   END;
 

  EXECUTE IMMEDIATE 'DROP VIEW TEMP_RS_324234523423';
--
--   EXECUTE IMMEDIATE
--         ' CREATE OR REPLACE SYNONYM FTP_AUDIT_TAB_'
--      || YEARMONTH
--      || ' FOR AUTO_FTP_AUDIT_TAB_'
--      || YEARMONTH
--      || '  ';

   
   
BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE AUTO_FTP_AUDIT_TAB_'|| YEARMONTH|| ' ADD FTP_RATE_NEW AS (CASE WHEN METHOD_TYPE IN (''CASACORE'') AND BALANCE <>0  THEN
  ROUND (DECODE (  (BALANCE),0, 1,(  (FTP_TOTAL)) /   (BALANCE))* 36500,2) ELSE FTP_RATE_TOTAL END )';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++++1');
         END IF;
   END;
   
   
BEGIN
   EXECUTE IMMEDIATE 'ALTER TABLE AUTO_FTP_AUDIT_TAB_'|| YEARMONTH|| ' ADD  FTP_MARGIN AS (
    CASE WHEN FTP_GROUP IN (''LOAN'',''OVERD'',''CREDITCARD'',''CBI'',''INTREC'') THEN  CUSTOMER_INTEREST - FTP_RATE_NEW
    WHEN FTP_GROUP IN (''FD'',''CASA'',''INTPAY'') THEN FTP_RATE_NEW- CUSTOMER_INTEREST
    ELSE  CUSTOMER_INTEREST - FTP_RATE_NEW END)';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++++1');
         END IF;
   END;
   
BEGIN
      EXECUTE IMMEDIATE 'CREATE OR REPLACE  VIEW   FTP_AUDIT_TAB_'|| YEARMONTH|| '          AS 
SELECT YEAR_MONTH, BUSINESS_DATE, VISION_SBU, CUSTOMER_ID, CONTRACT_ID, CUSTOMER_NAME, CURRENCY, EXCHANGE_RATE, 
MIS_CURRENCY, FTP_GROUP, FTP_REFERENCE, FTP_SOURCE_REFERENCE, FTP_METHOD_REFERENCE, METHOD_TYPE, 
REPRICING_FLAG, FTP_TENOR_TYPE, LP_TENOR_TYPE,
START_DATE, MATURITY_DATE, START_REPRICE_DATE, NEXT_REPRICE_DATE, REPRICING_TERM, REPRICING_TERM_CODE, BALANCE, FTP_TOTAL, 
FTP_RATE_NEW FTP_RATE_TOTAL, CUSTOMER_INTEREST, FTP_MARGIN, FTP_CURVE_ID, FTP_RATE_ID, FTP_CURVE, FTP_ADDON, FTP_SUBSIDY, 
LP_RATE_ID, LP_RATE, FTP_AMOUNT, FTP_ADJUSTMENT, PREMIUM, ADDON_DEPOSIT_RATE, ADDON_DEPOSIT_AMT, SUBSIDY_RATE, SUBSIDY_AMT,
ADDON_LENDING_RATE, ADDON_LENDING_AMT, REQUIRED_RESERVE_RATE, REQUIRED_RESERVE_AMT, GL_ALLOCATION_RATE, GL_ALLOCATION_AMT,
ADDON_ATT_RATE1, ADDON_ATT_AMT1, OFFICE_ACCOUNT, GL_ENRICH_ID, BS_GL, PL_GL, VISION_OUC, ACCOUNT_OFFICER,
COST_CENTER, SOURCE_OF_FUND, SOURCE_ID, RECORD_TYPE, ORIGINAL_OUC, 
COUNTRY, LE_BOOK, SEQUENCE_FD, SEQUENCE_FD_NEW, VERSION_NO, SBU_AUDIT
FROM AUTO_FTP_AUDIT_TAB_'|| YEARMONTH|| '';
   EXCEPTION
      WHEN OTHERS
      THEN
         IF SQLCODE != -0942
         THEN
            DBMS_OUTPUT.PUT_LINE ('++++1');
         END IF;
   END;

 

   COMMIT;
   
     EXECUTE IMMEDIATE
         'UPDATE FTP_GROUPS A SET FTP_DEFAULT_FLAG=''Y'' 
 WHERE FTP_GROUP_SEQ
 =(SELECT MAX(FTP_GROUP_SEQ) FROM FTP_GROUPS B
 WHERE A.FTP_GROUP=B.FTP_GROUP) ';

   COMMIT;
--   
--   EXECUTE IMMEDIATE
--         'UPDATE FTP_GROUPS SET FTP_GRP_STATUS=9
--WHERE FTP_REFERENCE IN (''OBGNOSVOS'',''OBGNOSVOS'',''QLTDLNMLPZ'',''SOELN1MLPZ'',''LNNANOLPX'',''LNFIX'',''SOELN1MNLX'',''QLTD1MNLX'',''QLTDLNMLPX'',''SOELN1MLPX'',''LCLN1MLPX'',''FILN1MLPX'',''TAINGUYEN'',''BSM9_SOE'',''BSM8_EB''
--,''BSM8_EB'',''CBIREPO'',''FICOF4'',''THTRUEMILK'',''BACAFUNDIN'',''FICASA1MFD'',''VAMCCB'',''FRMM01'',''FRMM03'',''FRMM05'',''FRMM06'',''FRMM07'',''FRMM08'',''QLTDLN12M'',''SOELN12M''
--,''FISPECPRO'',''SOESPECPRO'',''RBFD36M'',''FRRB29MAR'',''BSM1LC'',''BSM2RB'',''BSM3RB'',''FILN1MLP'',''LCLN1M'',''LCLN3M'',''LNFI'',''LNFI_USD'',''LNQLTD_USD'',''LNRBUSDLP''
--,''QLTD1MNL'',''QLTDLN1MLP'',''QLTDMATTER'',''RBLN11M12'',''SMECOF1M'',''SMECOF1MN'',''SMECOF3M'',''SMECOF3MRE'',''SOELN1MNL'',''BSM14'',''EQTYPAYABL'',''FRMM04''   
--) ';
--
--   COMMIT;
   
   
   
END;
/
