--
--CREATE TABLE TEMP_RS_3254345345234 NOLOGGING PARALLEL AS
--
--SELECT /*+PARALLEL(3)*/ * FROM denorm_days
--
--SELECT /*+ INDEX(T3) parallel(10) */
--      t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH, '402' ADJ_SOURCE_AT, 'DC'ADJ_SOURCE, 1 SEQUENCE_FD,'FW202007'  ADJ_REFERENCE,
--'851' ADJ_ID, 1 SEQUENCE_FA, 'D000' CUSTOMER_ID, 0   GL_ENRICH_ID, 0 CONTRACT_ID,   OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC, 3 VISION_SBU_AT, VISION_SBU, 
--'NA'  ACCOUNT_OFFICER, 'NA' COST_CENTER, CURRENCY, MIS_CURRENCY, 34 ACCRUAL_STATUS_NT, 9999 ACCRUAL_STATUS, 'NA' CREDIT_LINE, 'NOPOOL' POOL_CODE, 23 SOURCE_ID_NT,998  SOURCE_ID, 
--22 RECORD_TYPE_NT, 7 RECORD_TYPE, ORIGINAL_OUC,24  BAL_TYPE_NT, 57 BAL_TYPE, TO_DATE('31-jul-2020') TRANS_DATE, TO_DATE('31-jul-2020') VALUE_DATE,          -    SUM (BALANCE_01  +
--                  BALANCE_02  +
--                  BALANCE_03  +
--                  BALANCE_04  +
--                  BALANCE_05  +
--                  BALANCE_06  +
--                  BALANCE_07  +
--                  BALANCE_08  +
--                  BALANCE_09  +
--                  BALANCE_10  +
--                  BALANCE_11  +
--                  BALANCE_12  +
--                  BALANCE_13  +
--                  BALANCE_14  +
--                  BALANCE_15  +
--                  BALANCE_16  +
--                  BALANCE_17  +
--                  BALANCE_18  +
--                  BALANCE_19  +
--                  BALANCE_20  +
--                  BALANCE_21  +
--                  BALANCE_22  +
--                  BALANCE_23  +
--                  BALANCE_24  +
--                  BALANCE_25  +
--                  BALANCE_26  +
--                  BALANCE_27  +
--                  BALANCE_28  +
--                  BALANCE_29  +
--                  BALANCE_30  +
--                  BALANCE_31  ) TRANS_AMOUNT, NULL FINANCIAL_ATTRIBUTE_1, NULL FINANCIAL_ATTRIBUTE_2, NULL 
--FINANCIAL_ATTRIBUTE_3, 'X' SOURCE_FLAG, 1029 MAKER, 0 VERIFIER, 0 INTERNAL_STATUS, SYSDATE DATE_LAST_MODIFIED, SYSDATE DATE_CREATION
--    FROM FIN_DLY_HEADERS T1, FIN_DLY_BALANCES T2 
--   WHERE     T1.COUNTRY = T2.COUNTRY
--         AND T1.LE_BOOK = T2.LE_BOOK
--         AND T1.YEAR_MONTH = T2.YEAR_MONTH
--         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD 
--         AND T1.COUNTRY = 'VN'
--         AND T1.LE_BOOK = '01'
--         AND T1.YEAR_MONTH = '202007'
--         AND T1.RECORD_TYPE <> 9999
--         AND T2.BAL_TYPE IN (54)
--         AND PL_GL IN (440201001,530201001,440401001,440401201,530401001,530401201)
--         AND substr(ORIGINAL_OUC,5,4) not in ('0011')
--        GROUP BY t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH,  OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC,ORIGINAL_OUC,VISION_SBU,CURRENCY, MIS_CURRENCY 
--
--       
--         
--         

SELECT /*+PARALLEL(3)*/ * FROM FIN_DLY_HEADERS WHERE COUNTRY='VN' AND LE_BOOK='01' AND YEAR_MONTH=202007
         
  
DELETE FROM FIN_DLY_ADJ_HEADERS WHERE ADJ_REFERENCE IN ('FW202007','FW202007')
/
  
SET DEFINE OFF;
Insert into VISION.FIN_DLY_ADJ_HEADERS
(COUNTRY, LE_BOOK, YEAR_MONTH, ADJ_SOURCE_AT, ADJ_SOURCE, 
ADJ_REFERENCE, DATA_TYPE_AT, DATA_TYPE, FA_REASON_CODE_NT, FA_REASON_CODE, 
SUPPLEMENT, ORIGINATING_OUC, FIN_DLY_ADJ_HEADERS_STATUS_NT, FIN_DLY_ADJ_HEADERS_STATUS, RECORD_INDICATOR_NT, 
RECORD_INDICATOR, MAKER, VERIFIER, INTERNAL_STATUS, DATE_LAST_MODIFIED, 
DATE_CREATION)
Values
('VN', '01', 202007, 402, 'DC', 
'FW202007', 301, 'LB', 171, 5, 
'FW rev ', 'VN01001100000000', 101, 10, 175, 
0, 1029, 0, 0, TO_DATE('07/08/2020 19:35:56', 'MM/DD/YYYY HH24:MI:SS'), 
TO_DATE('07/08/2020 19:32:14', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
  

DELETE /*+PARALLEL(30)*/ FROM FIN_DLY_ADJ_POSTINGS WHERE COUNTRY='VN' AND LE_BOOK='01' AND YEAR_MONTH=202007 AND  ADJ_REFERENCE IN ('FW202007')
/
 

insert into FIN_DLY_ADJ_POSTINGS 
SELECT COUNTRY, LE_BOOK, YEAR_MONTH, ADJ_SOURCE_AT, ADJ_SOURCE,  SEQUENCE_FD, ADJ_REFERENCE, ADJ_ID, ROWNUM SEQUENCE_FA, CUSTOMER_ID, GL_ENRICH_ID, 
CONTRACT_ID, OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC, VISION_SBU_AT, VISION_SBU, ACCOUNT_OFFICER, COST_CENTER, CURRENCY, MIS_CURRENCY, 
ACCRUAL_STATUS_NT, ACCRUAL_STATUS, CREDIT_LINE, POOL_CODE, SOURCE_ID_NT, SOURCE_ID, RECORD_TYPE_NT, RECORD_TYPE, ORIGINAL_OUC, BAL_TYPE_NT, BAL_TYPE, TRANS_DATE, VALUE_DATE, TRANS_AMOUNT, FINANCIAL_ATTRIBUTE_1, FINANCIAL_ATTRIBUTE_2, FINANCIAL_ATTRIBUTE_3, SOURCE_FLAG, MAKER, VERIFIER, INTERNAL_STATUS, DATE_LAST_MODIFIED, DATE_CREATION
FROM
(SELECT /*+ INDEX(T3) parallel(10) */
      t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH, '402' ADJ_SOURCE_AT, 'DC'ADJ_SOURCE, 1 SEQUENCE_FD,'FW202007'  ADJ_REFERENCE,
'851' ADJ_ID, 1 SEQUENCE_FA,  'D000' CUSTOMER_ID, 0   GL_ENRICH_ID,  0 CONTRACT_ID,   OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC, 3 VISION_SBU_AT, VISION_SBU, 
'NA'  ACCOUNT_OFFICER, 'NA' COST_CENTER, CURRENCY, MIS_CURRENCY, 34 ACCRUAL_STATUS_NT, 9999 ACCRUAL_STATUS, 'NA' CREDIT_LINE, 'NOPOOL' POOL_CODE, 23 SOURCE_ID_NT,998  SOURCE_ID, 
22 RECORD_TYPE_NT, 7 RECORD_TYPE,
 REPLACE(ORIGINAL_OUC,'VN01VN01','VN01')ORIGINAL_OUC,24  BAL_TYPE_NT, 54 BAL_TYPE, TO_DATE('31-jul-2020') TRANS_DATE, TO_DATE('31-jul-2020') VALUE_DATE,    
      -    SUM (BALANCE_01  +
                  BALANCE_02  +
                  BALANCE_03  +
                  BALANCE_04  +
                  BALANCE_05  +
                  BALANCE_06  +
                  BALANCE_07  +
                  BALANCE_08  +
                  BALANCE_09  +
                  BALANCE_10  +
                  BALANCE_11  +
                  BALANCE_12  +
                  BALANCE_13  +
                  BALANCE_14  +
                  BALANCE_15  +
                  BALANCE_16  +
                  BALANCE_17  +
                  BALANCE_18  +
                  BALANCE_19  +
                  BALANCE_20  +
                  BALANCE_21  +
                  BALANCE_22  +
                  BALANCE_23  +
                  BALANCE_24  +
                  BALANCE_25  +
                  BALANCE_26  +
                  BALANCE_27  +
                  BALANCE_28  +
                  BALANCE_29  +
                  BALANCE_30  +
                  BALANCE_31  ) TRANS_AMOUNT, NULL FINANCIAL_ATTRIBUTE_1, NULL FINANCIAL_ATTRIBUTE_2, NULL 
FINANCIAL_ATTRIBUTE_3, 'X' SOURCE_FLAG, 1029 MAKER, 0 VERIFIER, 0 INTERNAL_STATUS, SYSDATE DATE_LAST_MODIFIED, SYSDATE DATE_CREATION
    FROM FIN_DLY_HEADERS T1, FIN_DLY_BALANCES T2 
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD 
         AND T1.COUNTRY = 'VN'
         AND T1.LE_BOOK = '01'
         AND T1.YEAR_MONTH = '202007'
         AND T1.RECORD_TYPE <> 9999
         AND T2.BAL_TYPE IN (54)
         AND BALANCE_31<>0
         AND PL_GL IN (440201001,530201001,440401001,440401201,530401001,530401201)
         AND substr(ORIGINAL_OUC,5,4) not in ('0011')
        GROUP BY t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH,  OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC,ORIGINAL_OUC,VISION_SBU,CURRENCY, MIS_CURRENCY
--        ,
--        CUSTOMER_ID, CONTRACT_ID 
        )
        
        
        
 / 
 
DELETE FROM FIN_DLY_ADJ_DETAILS WHERE ADJ_REFERENCE IN ('FW202007' )
/
insert into FIN_DLY_ADJ_DETAILS 
select COUNTRY, LE_BOOK, YEAR_MONTH, ADJ_SOURCE_AT, ADJ_SOURCE, ADJ_REFERENCE, ADJ_ID, 'Y' OVERRIDE_IMBALANCE,sum(TRANS_AMOUNT) BATCH_TOTAL_AMOUNT,count(1) POSTINGS_COUNT, to_date('31-jul-2020')VALIDATION_DATE, to_date('31-jul-2020')POSTED_DATE,101  FIN_DLY_ADJ_DETAILS_STATUS_NT, 10 FIN_DLY_ADJ_DETAILS_STATUS,  7 RECORD_INDICATOR_NT, 0 RECORD_INDICATOR, MAKER, VERIFIER, INTERNAL_STATUS, DATE_LAST_MODIFIED, DATE_CREATION
from (SELECT /*+ INDEX(T3) parallel(10) */
      t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH, '402' ADJ_SOURCE_AT, 'DC'ADJ_SOURCE, 1 SEQUENCE_FD,'FW202007'  ADJ_REFERENCE,
'851' ADJ_ID, 1 SEQUENCE_FA, 'D000' CUSTOMER_ID, 0   GL_ENRICH_ID, 0 CONTRACT_ID,   OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC, 3 VISION_SBU_AT, VISION_SBU, 
'NA'  ACCOUNT_OFFICER, 'NA' COST_CENTER, CURRENCY, MIS_CURRENCY, 34 ACCRUAL_STATUS_NT, 9999 ACCRUAL_STATUS, 'NA' CREDIT_LINE, 'NOPOOL' POOL_CODE, 23 SOURCE_ID_NT,998  SOURCE_ID, 
22 RECORD_TYPE_NT, 7 RECORD_TYPE, ORIGINAL_OUC,24  BAL_TYPE_NT, 57 BAL_TYPE, TO_DATE('31-jul-2020') TRANS_DATE, TO_DATE('31-jul-2020') VALUE_DATE,     
     -    SUM (BALANCE_01  +
                  BALANCE_02  +
                  BALANCE_03  +
                  BALANCE_04  +
                  BALANCE_05  +
                  BALANCE_06  +
                  BALANCE_07  +
                  BALANCE_08  +
                  BALANCE_09  +
                  BALANCE_10  +
                  BALANCE_11  +
                  BALANCE_12  +
                  BALANCE_13  +
                  BALANCE_14  +
                  BALANCE_15  +
                  BALANCE_16  +
                  BALANCE_17  +
                  BALANCE_18  +
                  BALANCE_19  +
                  BALANCE_20  +
                  BALANCE_21  +
                  BALANCE_22  +
                  BALANCE_23  +
                  BALANCE_24  +
                  BALANCE_25  +
                  BALANCE_26  +
                  BALANCE_27  +
                  BALANCE_28  +
                  BALANCE_29  +
                  BALANCE_30  +
                  BALANCE_31  ) TRANS_AMOUNT, NULL FINANCIAL_ATTRIBUTE_1, NULL FINANCIAL_ATTRIBUTE_2, NULL 
FINANCIAL_ATTRIBUTE_3, 'X' SOURCE_FLAG, 1029 MAKER, 0 VERIFIER, 0 INTERNAL_STATUS, SYSDATE DATE_LAST_MODIFIED, SYSDATE DATE_CREATION
    FROM FIN_DLY_HEADERS T1, FIN_DLY_BALANCES T2 
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD 
         AND T1.COUNTRY = 'VN'
         AND T1.LE_BOOK = '01'
         AND T1.YEAR_MONTH = '202007'
         AND T1.RECORD_TYPE <> 9999
         AND T2.BAL_TYPE IN (54)
         AND PL_GL IN (440201001,530201001,440401001,440401201,530401001,530401201)
         AND substr(ORIGINAL_OUC,5,4) not in ('0011')
        GROUP BY t1.COUNTRY, t1.LE_BOOK, t1.YEAR_MONTH,  OFFICE_ACCOUNT, BS_GL, PL_GL, VISION_OUC,ORIGINAL_OUC,VISION_SBU,CURRENCY, MIS_CURRENCY )
GROUP BY COUNTRY, LE_BOOK, YEAR_MONTH, ADJ_SOURCE_AT, ADJ_SOURCE, ADJ_REFERENCE, ADJ_ID,MAKER, VERIFIER, INTERNAL_STATUS, DATE_LAST_MODIFIED, DATE_CREATION
/
 
  
  
++++++++

  SELECT TRAN_ID TRN_REF_NO,
         TRAN_ID TRN_CODE,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    FROM TRANSCNT_FEED_STG  A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE     A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE  >= '01-jul-2020'
         AND A.VALUE_DATE  <= '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012', '290106002' ) 
         AND TRAN_SUB_TYPE<>'X'
         GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU 
         UNION ALL  
  SELECT TRAN_ID TRN_REF_NO,
         TRAN_ID TRN_CODE,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_PARTICULAR SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    FROM (SELECT ' ' CUSTOMER_ID, FODEALID CONTRACT_ID, GTACCT VISION_GL, TREFTH TRAN_PARTICULAR, TRTKTN TRAN_ID,  TRCTYP TRAN_CCY,TRDORC TRAN_TYPE,
 TRSRC TRAN_SUB_TYPE,TRDORC PART_TRAN_TYPE, TRAMT TRAN_AMT, TO_DATE(TRJDAT,'RRRRDDD') TRAN_DATE,TO_DATE(TRJEFF,'RRRRDDD') VALUE_DATE, 
 TRBR PROCESS_OUC, TO_DATE(TRJDAT,'RRRRDDD') FEED_DATE, TRAUXT, TRTIME, TRCORF, TRCFYR 
 FROM HSTAGING.K_MSBRPT_RP_GLTTRN@HSTAGING_PROD WHERE GTACCT in (290106002,290106004,290106012)
AND TRJEFF BETWEEN TO_CHAR(TO_DATE('01-jul-2020'),'RRRRDDD')
AND TO_CHAR(TO_DATE('31-jul-2020'),'RRRRDDD'))  A,
         (  SELECT /*+PARALLEL(3)*/
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY  CONTRACT_ID) B 
         WHERE  TO_CHAR(A.CONTRACT_ID) = TO_CHAR(B.CONTRACT_ID(+))
         AND A.VALUE_DATE  >= '01-jul-2020'
         AND A.VALUE_DATE  <= '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012', '290106002' ) 
         AND TRAN_SUB_TYPE='X'
         GROUP BY TRAN_ID,
         TRAN_ID,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_PARTICULAR,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU
		 

SELECT TRAN_ID TRN_REF_NO,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         'TS' MODULE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    -- , PGDS
    FROM TRANSCNT_FEED_STG_PL_1 A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE       A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE  = '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012','530401001','290106002','440401001','440401202',
        '530401202','440202001','530202001','530401201','440401201')
GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU
          
         
         
         
  SELECT TRAN_ID TRN_REF_NO,
         TRAN_RMKS TRN_CODE,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    FROM TRANSCNT_FEED_STG  A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE     A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE  = '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012', '290106002' ) 
         GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU
          
*****************************************		  


  SELECT TRAN_ID TRN_REF_NO,
         TRAN_RMKS TRN_CODE,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         'TS' MODULE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    -- , PGDS
    FROM TRANSCNT_FEED_STG A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE      TRAN_SUB_TYPE = 'X'
         AND A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE BETWEEN '01-jul-2020' AND '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012','530401001','290106002','440401001','440401202',
        '530401202','440202001','530202001','530401201','440401201')
GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU
          


  SELECT TRAN_ID TRN_REF_NO,
         TRAN_RMKS TRN_CODE,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         'TS' MODULE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    -- , PGDS
    FROM TRANSCNT_FEED_STG_PL_1 A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE     BUSINESS_DATE = '202007'
         AND TRAN_SUB_TYPE = 'X'
         AND A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND a.VALUE_DATE='31-jul-2020'
GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU