-- BS

SELECT TRAN_ID TRN_REF_NO,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         'TS' MODULE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    -- , PGDS
    FROM TRANSCNT_FEED_STG_PL A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE       A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE  >= '01-jul-2020'
         AND A.VALUE_DATE  <= '31-jul-2020'
         AND VISION_GL IN ('290106004','290106012','290106002')
GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU


SELECT TRAN_ID TRN_REF_NO,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END BACKDATE,
         'TS' MODULE,
         PROCESS_OUC TRN_BRANCH_CODE,
         FEED_DATE TRN_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE DORC_IND,
         SUM (TRAN_AMT) ACY_AMOUNT,
         TRAN_CCY CURRENCY,
         0 EXCHANGE_RATE,
         SUM (TRAN_AMT) LCY_AMOUNT,
         VISION_OUC AC_BRANCH_CODE,
         A.CONTRACT_ID ACCOUNT_NO,
         VISION_GL GL_CODE,
         TRAN_SUB_TYPE TRN_SOURCE,
         TRAN_DESCRIPTION SRC_REF_NO,
         A.CUSTOMER_ID CUSTOMER_NO,
         VISION_SBU BUSINESS_UNIT,
         DEAL_SUB_TYPE PRODUCT_CODE,
         VISION_SBU BUSINESS_LINE,
         (SELECT CUSTOMER_NAME
            FROM CUSTOMERS C
           WHERE C.CUSTOMER_ID = A.CUSTOMER_ID)
            CUSTOMER_NAME
    -- , PGDS
    FROM TRANSCNT_FEED_STG_PL A,
         (  SELECT /*+PARALLEL(3)*/
                  CUSTOMER_ID,
                   CONTRACT_ID,
                   MAX (VISION_OUC) VISION_OUC,
                   MAX (VISION_SBU) VISION_SBU,
                   MAX (DEAL_SUB_TYPE) DEAL_SUB_TYPE
              FROM CONTRACTS
          GROUP BY CUSTOMER_ID, CONTRACT_ID) B
   WHERE       A.CUSTOMER_ID = B.CUSTOMER_ID(+)
         AND A.CONTRACT_ID = B.CONTRACT_ID(+)
         AND A.VALUE_DATE  >= '01-jul-2020'
         AND A.VALUE_DATE  <= '31-jul-2020'
         AND VISION_GL IN ('530401001','440401001','440401202',
        '530401202','440202001','530202001','530401201','440401201')
GROUP BY TRAN_ID,
         TRAN_RMKS,
         CASE WHEN FEED_DATE <> VALUE_DATE THEN 'Y' ELSE 'N' END,
         PROCESS_OUC,
         FEED_DATE,
         VALUE_DATE,
         PART_TRAN_TYPE,
         TRAN_CCY,
         VISION_OUC,
         A.CONTRACT_ID,
         VISION_GL,
         TRAN_SUB_TYPE,
         TRAN_DESCRIPTION,
         A.CUSTOMER_ID,
         VISION_SBU,
         DEAL_SUB_TYPE,
         VISION_SBU