/*--+===========================================================================================================================================+
                                                MA Daily Avg & FTP (Pool)
+===========================================================================================================================================+ 

Replace Following Parameters
----------

Year_month :  202005
Adjust number of days : 31
Exclude Vision_sbu : FI
Currency :  VND,USD

--+===========================================================================================================================================+*/ 



-- MA dly

  SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */
        DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
            FRL_CATEGORY,
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         SUM (BALANCE_15 * RATE_15),
         DECODE (T2.BAL_TYPE,  51, 1,  57, 4,  58, 4) BAL_TYPE,
         PARENT_SBU_DESCRIPTION SBU
    FROM VISION.VW_FIN_DLY_HEADERS T1,
         VISION.FIN_DLY_BALANCES T2,
         VISION.FIN_DLY_MAPPINGS T3,
         VISION.MGT_EXPANDED T8,
         VISION_SBU Q,
         CURRENCY_RATES_DAILY T4
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
         AND T2.COUNTRY = T3.COUNTRY
         AND T2.LE_BOOK = T3.LE_BOOK
         AND T2.YEAR_MONTH = T3.YEAR_MONTH
         AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
         AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
         AND T1.YEAR_MONTH IN ('202006')
         AND T1.RECORD_TYPE != 9999
         AND T2.BAL_TYPE IN (51, 57, 58)
         AND MGT_LINE <> 'G010000'
         AND T8.MGT_LINE_LEVEL = 1
         AND T8.SOURCE_BAL_TYPE = 1
         AND T8.SOURCE_TYPE = 0
         AND T3.MRL_LINE = SOURCE_MRL_LINE
         AND T1.CURRENCY IN ('VND', 'USD')
         AND T1.VISION_SBU <> 'FI'
         AND T1.VISION_SBU = Q.VISION_SBU
         AND T1.COUNTRY = T4.COUNTRY
         AND T1.LE_BOOK = T4.LE_BOOK
         AND T1.YEAR_MONTH = T4.YEAR_MONTH
         AND T1.CURRENCY = T4.CURRENCY
         AND T4.CATEGORY = 'MRATE'
GROUP BY DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability'),
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         DECODE (T2.BAL_TYPE,  51, 1,  57, 4,  58, 4),
         PARENT_SBU_DESCRIPTION,
         DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
ORDER BY MGT_LINE


-- MA FI  

  SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */
        DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
            FRL_CATEGORY,
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         SUM (BALANCE_15 * RATE_15) BAL_LCY,
         SUM (BALANCE_15         )  BAL_FCY,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 ) BAL_TYPE  ,
         PARENT_SBU_DESCRIPTION SBU
    FROM VISION.VW_FIN_DLY_HEADERS T1,
         VISION.FIN_DLY_BALANCES T2,
         VISION.FIN_DLY_MAPPINGS T3,
         VISION.MGT_EXPANDED T8,
         VISION_SBU Q,
         CURRENCY_RATES_DAILY T4
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
         AND T2.COUNTRY = T3.COUNTRY
         AND T2.LE_BOOK = T3.LE_BOOK
         AND T2.YEAR_MONTH = T3.YEAR_MONTH
         AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
         AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
         AND T1.YEAR_MONTH IN ('202006')
         AND T1.RECORD_TYPE != 9999
         AND T2.BAL_TYPE IN (51, 54)
         AND MGT_LINE <> 'G010000'
         AND T8.MGT_LINE_LEVEL = 1
         AND T8.SOURCE_BAL_TYPE = DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )
         AND T8.SOURCE_TYPE = 0
         AND T3.MRL_LINE = SOURCE_MRL_LINE
         AND T1.MIS_CURRENCY IN ( 'USD')
         AND CASE WHEN RECORD_TYPE = 3 AND T2.BAL_TYPE=54 THEN 'VND'
                      ELSE MIS_CURRENCY END IN 'USD'
         AND T1.VISION_SBU = 'FI'  
         AND T1.VISION_SBU = Q.VISION_SBU
         AND T1.COUNTRY = T4.COUNTRY
         AND T1.LE_BOOK = T4.LE_BOOK
         AND T1.YEAR_MONTH = T4.YEAR_MONTH
         AND T1.CURRENCY = T4.CURRENCY
         AND T4.CATEGORY = 'MRATE'
         AND BALANCE_15<>0
GROUP BY DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability'),
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )  ,
         PARENT_SBU_DESCRIPTION,
         DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
UNION ALL
  SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */
        DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
            FRL_CATEGORY,
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         SUM (BALANCE_15 * RATE_15) BAL_LCY,
         SUM (BALANCE_15         )  BAL_FCY,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 ) BAL_TYPE  ,
         PARENT_SBU_DESCRIPTION SBU
    FROM VISION.VW_FIN_DLY_HEADERS T1,
         VISION.FIN_DLY_BALANCES T2,
         VISION.FIN_DLY_MAPPINGS T3,
         VISION.MGT_EXPANDED T8,
         VISION_SBU Q,
         CURRENCY_RATES_DAILY T4
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
         AND T2.COUNTRY = T3.COUNTRY
         AND T2.LE_BOOK = T3.LE_BOOK
         AND T2.YEAR_MONTH = T3.YEAR_MONTH
         AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
         AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
         AND T1.YEAR_MONTH IN ('202006')
         AND T1.RECORD_TYPE != 9999
         AND T2.BAL_TYPE IN (51, 54)
         AND MGT_LINE <> 'G010000'
         AND T8.MGT_LINE_LEVEL = 1
         AND T8.SOURCE_BAL_TYPE = DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )
         AND T8.SOURCE_TYPE = 0
         AND T3.MRL_LINE = SOURCE_MRL_LINE
         AND T1.MIS_CURRENCY IN ( 'VND')
         AND CASE WHEN RECORD_TYPE = 3 AND T2.BAL_TYPE=54 THEN 'VND'
                      ELSE MIS_CURRENCY END IN 'VND'
         AND T1.VISION_SBU = 'FI'  
         AND T1.VISION_SBU = Q.VISION_SBU
         AND T1.COUNTRY = T4.COUNTRY
         AND T1.LE_BOOK = T4.LE_BOOK
         AND T1.YEAR_MONTH = T4.YEAR_MONTH
         AND T1.CURRENCY = T4.CURRENCY
         AND T4.CATEGORY = 'MRATE'
         AND BALANCE_15<>0
GROUP BY DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability'),
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )  ,
         PARENT_SBU_DESCRIPTION,
         DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
ORDER BY MGT_LINE

*************
-- MA dly

  SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */
        DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
            FRL_CATEGORY,
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         SUM (BALANCE_27 * RATE_27),
         DECODE (T2.BAL_TYPE,  51, 1,  57, 4,  58, 4) BAL_TYPE,
         PARENT_SBU_DESCRIPTION SBU
    FROM VISION.VW_FIN_DLY_HEADERS T1,
         VISION.FIN_DLY_BALANCES T2,
         VISION.FIN_DLY_MAPPINGS T3,
         VISION.MGT_EXPANDED T8,
         VISION_SBU Q,
         CURRENCY_RATES_DAILY T4
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
         AND T2.COUNTRY = T3.COUNTRY
         AND T2.LE_BOOK = T3.LE_BOOK
         AND T2.YEAR_MONTH = T3.YEAR_MONTH
         AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
         AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
         AND T1.YEAR_MONTH IN ('202005')
         AND T1.RECORD_TYPE != 9999
         AND T2.BAL_TYPE IN (51, 57, 58)
         AND MGT_LINE <> 'G010000'
         AND T8.MGT_LINE_LEVEL = 1
         AND T8.SOURCE_BAL_TYPE = 1
         AND T8.SOURCE_TYPE = 0
         AND T3.MRL_LINE = SOURCE_MRL_LINE
         AND T1.CURRENCY IN ('VND', 'USD')
         AND T1.VISION_SBU <> 'FI'
         AND T1.VISION_SBU = Q.VISION_SBU
         AND T1.COUNTRY = T4.COUNTRY
         AND T1.LE_BOOK = T4.LE_BOOK
         AND T1.YEAR_MONTH = T4.YEAR_MONTH
         AND T1.CURRENCY = T4.CURRENCY
         AND T4.CATEGORY = 'MRATE'
GROUP BY DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability'),
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         DECODE (T2.BAL_TYPE,  51, 1,  57, 4,  58, 4),
         PARENT_SBU_DESCRIPTION,
         DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
ORDER BY MGT_LINE


-- MA FI 

  SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */
        DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
            FRL_CATEGORY,
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         SUM (BALANCE_10 * RATE_10) BAL_LCY,
         SUM (BALANCE_10         )  BAL_FCY,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 ) BAL_TYPE  ,
         PARENT_SBU_DESCRIPTION SBU
    FROM VISION.VW_FIN_DLY_HEADERS T1,
         VISION.FIN_DLY_BALANCES T2,
         VISION.FIN_DLY_MAPPINGS T3,
         VISION.MGT_EXPANDED T8,
         VISION_SBU Q,
         CURRENCY_RATES_DAILY T4
   WHERE     T1.COUNTRY = T2.COUNTRY
         AND T1.LE_BOOK = T2.LE_BOOK
         AND T1.YEAR_MONTH = T2.YEAR_MONTH
         AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
         AND T2.COUNTRY = T3.COUNTRY
         AND T2.LE_BOOK = T3.LE_BOOK
         AND T2.YEAR_MONTH = T3.YEAR_MONTH
         AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
         AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
         AND T1.YEAR_MONTH IN ('202005')
         AND T1.RECORD_TYPE != 9999
         AND T2.BAL_TYPE IN (51, 54)
         AND MGT_LINE <> 'G010000'
         AND T8.MGT_LINE_LEVEL = 1
         AND T8.SOURCE_BAL_TYPE = DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )
         AND T8.SOURCE_TYPE = 0
         AND T3.MRL_LINE = SOURCE_MRL_LINE
         AND T1.MIS_CURRENCY IN ( 'VND','USD')
         AND T1.VISION_SBU = 'FI'  
         AND T1.VISION_SBU = Q.VISION_SBU
         AND T1.COUNTRY = T4.COUNTRY
         AND T1.LE_BOOK = T4.LE_BOOK
         AND T1.YEAR_MONTH = T4.YEAR_MONTH
         AND T1.CURRENCY = T4.CURRENCY
         AND T4.CATEGORY = 'MRATE'
         AND BALANCE_10<>0
GROUP BY DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability'),
         T1.VISION_SBU,
         T1.MIS_CURRENCY,
         MGT_LINE,
         MGT_LINE_DESCRIPTION,
         T2.BAL_TYPE,
         DECODE (T2.BAL_TYPE,  51, 1,  54, 3 )  ,
         PARENT_SBU_DESCRIPTION,
         DECODE (MGT_TYPE,  10, 'Asset',  20, 'Liability',  35, 'Offset')
ORDER BY MGT_LINE



SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */  
DECODE(MGT_TYPE,10,'Asset',20,'Liability',35,'Offset') FRL_CATEGORY   , T1.VISION_SBU ,   T1.MIS_CURRENCY  ,  
MGT_LINE ,   MGT_LINE_DESCRIPTION  ,  T2.BAL_TYPE   ,
sum(case when t2.bal_type = 51 then 
((BALANCE_01 * RATE_01) +
 (BALANCE_02 * RATE_02) +
 (BALANCE_03 * RATE_03) +
 (BALANCE_04 * RATE_04) +
 (BALANCE_05 * RATE_05) +
 (BALANCE_06 * RATE_06) +
 (BALANCE_07 * RATE_07) +
 (BALANCE_08 * RATE_08) +
 (BALANCE_09 * RATE_09) +
 (BALANCE_10 * RATE_10) +
 (BALANCE_11 * RATE_11) +
 (BALANCE_12 * RATE_12) +
 (BALANCE_13 * RATE_13) +
 (BALANCE_14 * RATE_14) +
 (BALANCE_15 * RATE_15) +
 (BALANCE_16 * RATE_16) +
 (BALANCE_17 * RATE_17) +
 (BALANCE_18 * RATE_18) +
 (BALANCE_19 * RATE_19) +
 (BALANCE_20 * RATE_20) +
 (BALANCE_21 * RATE_21) +
 (BALANCE_22 * RATE_22) +
 (BALANCE_23 * RATE_23) +
 (BALANCE_24 * RATE_24) +
 (BALANCE_25 * RATE_25) +
 (BALANCE_26 * RATE_26) +
 (BALANCE_27 * RATE_27) + 
 (BALANCE_28 * RATE_28) +
 (BALANCE_29 * RATE_29) +
 (BALANCE_30 * RATE_30) + 
 (BALANCE_31 * RATE_31)  
 )/31  else 
((BALANCE_01 * RATE_01) +
 (BALANCE_02 * RATE_02) +
 (BALANCE_03 * RATE_03) +
 (BALANCE_04 * RATE_04) +
 (BALANCE_05 * RATE_05) +
 (BALANCE_06 * RATE_06) +
 (BALANCE_07 * RATE_07) +
 (BALANCE_08 * RATE_08) +
 (BALANCE_09 * RATE_09) +
 (BALANCE_10 * RATE_10) +
 (BALANCE_11 * RATE_11) +
 (BALANCE_12 * RATE_12) +
 (BALANCE_13 * RATE_13) +
 (BALANCE_14 * RATE_14) +
 (BALANCE_15 * RATE_15) +
 (BALANCE_16 * RATE_16) +
 (BALANCE_17 * RATE_17) +
 (BALANCE_18 * RATE_18) +
 (BALANCE_19 * RATE_19) +
 (BALANCE_20 * RATE_20) +
 (BALANCE_21 * RATE_21) +
 (BALANCE_22 * RATE_22) +
 (BALANCE_23 * RATE_23) +
 (BALANCE_24 * RATE_24) +
 (BALANCE_25 * RATE_25) +
 (BALANCE_26 * RATE_26) +
 (BALANCE_27 * RATE_27) + 
 (BALANCE_28 * RATE_28) +
 (BALANCE_29 * RATE_29) +
 (BALANCE_30 * RATE_30) + 
 (BALANCE_31 * RATE_31)  
 ) end)   M1_TODAY,  
 DECODE(T2.BAL_TYPE,51,1,57,4,58,4)  BAL_TYPE
,PARENT_SBU_DESCRIPTION  SBU
FROM 
VISION.VW_FIN_DLY_HEADERS T1,
VISION.FIN_DLY_BALANCES T2,
VISION.FIN_DLY_MAPPINGS T3, 
VISION.MGT_EXPANDED T8,
VISION_SBU Q,CURRENCY_RATES_DAILY T4
WHERE     T1.COUNTRY = T2.COUNTRY
AND T1.LE_BOOK = T2.LE_BOOK
AND T1.YEAR_MONTH = T2.YEAR_MONTH
AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
AND T2.COUNTRY = T3.COUNTRY
AND T2.LE_BOOK = T3.LE_BOOK
AND T2.YEAR_MONTH = T3.YEAR_MONTH
AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
AND T1.YEAR_MONTH IN ('202005')
AND T1.RECORD_TYPE != 9999
AND T2.BAL_TYPE IN (51,57,58) 
AND MGT_LINE <> 'G010000'  
AND T8.MGT_LINE_LEVEL = 1
AND T8.SOURCE_BAL_TYPE = 1
AND T8.SOURCE_TYPE = 0 
AND T3.MRL_LINE=SOURCE_MRL_LINE 
AND T1.CURRENCY IN ('VND','USD')
AND T1.VISION_SBU<>'FI'
AND T1.VISION_SBU=Q.VISION_SBU
AND T1.COUNTRY = T4.COUNTRY
AND T1.LE_BOOK = T4.LE_BOOK
AND T1.YEAR_MONTH = T4.YEAR_MONTH
AND T1.CURRENCY = T4.CURRENCY
AND T4.CATEGORY = 'MRATE'
GROUP BY DECODE(MGT_TYPE,10,'Asset',20,'Liability')     , T1.VISION_SBU ,   T1.MIS_CURRENCY  ,  
MGT_LINE ,   MGT_LINE_DESCRIPTION  ,  T2.BAL_TYPE,   DECODE(T2.BAL_TYPE,51,1,57,4,58,4)   
,PARENT_SBU_DESCRIPTION   ,DECODE(MGT_TYPE,10,'Asset',20,'Liability',35,'Offset')  
ORDER BY MGT_LINE


****

SELECT /*+ PARALLEL (T1 5) (T2 5) (T3 5) */  
DECODE(MGT_TYPE,10,'Asset',20,'Liability',35,'Offset') FRL_CATEGORY   , T1.VISION_SBU ,   T1.MIS_CURRENCY  ,  
MGT_LINE ,   MGT_LINE_DESCRIPTION  ,  T2.BAL_TYPE   ,
sum(case when t2.bal_type = 51 then 
( 
 (BALANCE_15 * RATE_15) 
 )/31  else 
( 
 (BALANCE_15 * RATE_15)  
 ) end)   M1_TODAY,  
 DECODE(T2.BAL_TYPE,51,1,57,4,58,4)  BAL_TYPE
,PARENT_SBU_DESCRIPTION  SBU
FROM 
VISION.VW_FIN_DLY_HEADERS T1,
VISION.FIN_DLY_BALANCES T2,
VISION.FIN_DLY_MAPPINGS T3, 
VISION.MGT_EXPANDED T8,
VISION_SBU Q,CURRENCY_RATES_DAILY T4
WHERE     T1.COUNTRY = T2.COUNTRY
AND T1.LE_BOOK = T2.LE_BOOK
AND T1.YEAR_MONTH = T2.YEAR_MONTH
AND T1.SEQUENCE_FD = T2.SEQUENCE_FD
AND T2.COUNTRY = T3.COUNTRY
AND T2.LE_BOOK = T3.LE_BOOK
AND T2.YEAR_MONTH = T3.YEAR_MONTH
AND T2.SEQUENCE_FD = T3.SEQUENCE_FD
AND T2.DR_CR_BAL_IND = T3.DR_CR_BAL_IND
AND T1.YEAR_MONTH IN ('202005')
AND T1.RECORD_TYPE != 9999
AND T2.BAL_TYPE IN (51,57,58) 
AND MGT_LINE <> 'G010000'  
AND T8.MGT_LINE_LEVEL = 1
AND T8.SOURCE_BAL_TYPE = 1
AND T8.SOURCE_TYPE = 0 
AND T3.MRL_LINE=SOURCE_MRL_LINE 
AND T1.CURRENCY IN ('VND','USD')
AND T1.VISION_SBU<>'FI'
AND T1.VISION_SBU=Q.VISION_SBU
AND T1.COUNTRY = T4.COUNTRY
AND T1.LE_BOOK = T4.LE_BOOK
AND T1.YEAR_MONTH = T4.YEAR_MONTH
AND T1.CURRENCY = T4.CURRENCY
AND T4.CATEGORY = 'MRATE'
GROUP BY DECODE(MGT_TYPE,10,'Asset',20,'Liability')     , T1.VISION_SBU ,   T1.MIS_CURRENCY  ,  
MGT_LINE ,   MGT_LINE_DESCRIPTION  ,  T2.BAL_TYPE,   DECODE(T2.BAL_TYPE,51,1,57,4,58,4)   
,PARENT_SBU_DESCRIPTION   ,DECODE(MGT_TYPE,10,'Asset',20,'Liability',35,'Offset')  
ORDER BY MGT_LINE