--Change parameter
--Year_month: 202107

DECLARE CNT NUMBER;
BEGIN 
    SELECT COUNT(*) INTO CNT FROM ALL_TABLES WHERE TABLE_NAME='VW_TRANSCNT_FEED_STG_PL_202107';
IF 
    CNT<>0 THEN EXECUTE IMMEDIATE 'DROP TABLE VW_TRANSCNT_FEED_STG_PL_202107';
END IF;
END;

/
CREATE TABLE VW_TRANSCNT_FEED_STG_PL_202107 AS
WITH TMP1
AS ( SELECT /*+ MATERIALIZE NOREWRITE */
CONTRACT_ID,
CUSTOMER_ID,
PL_GL,
MIN (VISION_SBU) KEEP (DENSE_RANK FIRST ORDER BY STT)
VISION_SBU
FROM ( SELECT /*+ PARALLEL(20) MATERIALIZE NOREWRITE */
CONTRACT_ID,
CUSTOMER_ID,
PL_GL,
MIN (VISION_SBU)
KEEP (DENSE_RANK FIRST ORDER BY SEQUENCE_FD)
VISION_SBU,
1 STT
FROM VISION.VW_FIN_DLY_HEADERS
WHERE COUNTRY = 'VN'
AND LE_BOOK = '01'
AND RECORD_TYPE <> 9999
AND YEAR_MONTH = '202107'
AND PL_GL <> 0
GROUP BY CONTRACT_ID, CUSTOMER_ID, PL_GL
UNION ALL
SELECT /*+ PARALLEL(20) MATERIALIZE NOREWRITE */
CONTRACT_ID,
CUSTOMER_ID,
PL_GL,
MIN (VISION_SBU)
KEEP (DENSE_RANK FIRST ORDER BY SEQUENCE_FD)
VISION_SBU,
2 STT
FROM VISION.FIN_DLY_HEADERS
WHERE COUNTRY = 'VN'
AND LE_BOOK = '01'
AND YEAR_MONTH = '202107'
AND PL_GL <> 0
GROUP BY CONTRACT_ID, CUSTOMER_ID, PL_GL)
GROUP BY CONTRACT_ID, CUSTOMER_ID, PL_GL)
SELECT /*+ PARALLEL (10) */
T1.COUNTRY,
T1.LE_BOOK,
TO_NUMBER (TO_CHAR (VALUE_DATE, 'YYYYMM')) YEAR_MONTH,
NVL (T2.VISION_SBU, 'NA') VISION_SBU,
TRAN_ID,
TRAN_DATE,
VALUE_DATE,
T1.CONTRACT_ID,
T1.CUSTOMER_ID,
VISION_GL,
PART_TRAN_TYPE,
TRAN_SUB_TYPE,
SCHM_TYPE,
TRAN_CCY,
TRAN_AMT,DECODE(PART_TRAN_TYPE,'D',-TRAN_AMT,TRAN_AMT) TRAN_AMT_DC,
PROCESS_OUC VISION_OUC,
TRAN_DESCRIPTION,
TRAN_PARTICULAR
FROM VISION.TRANSCNT_FEED_STG_PL T1
LEFT JOIN
TMP1 T2
ON ( T1.COUNTRY = 'VN'
AND T1.LE_BOOK = '01'
AND VALUE_DATE BETWEEN TO_DATE ('202107', ' YYYYMM')
AND LAST_DAY (TO_DATE ('202107', ' YYYYMM'))
AND T1.CONTRACT_ID = T2.CONTRACT_ID
AND T1.CUSTOMER_ID = T2.CUSTOMER_ID
AND T1.VISION_GL = T2.PL_GL)
WHERE T1.VALUE_DATE BETWEEN TO_DATE ('202107', ' YYYYMM')
AND LAST_DAY (TO_DATE ('202107', ' YYYYMM'))

/

UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='OP'
WHERE CONTRACT_ID LIKE 'OP%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='FDI'
WHERE CONTRACT_ID LIKE 'FDI%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='LC'
WHERE CONTRACT_ID LIKE 'LC%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='RB'
WHERE SCHM_TYPE='CARDS' AND VISION_SBU='NA'
--UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='FI'
--WHERE CUSTOMER_ID='FT00067311' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='FI'
WHERE CUSTOMER_ID='FT' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='FI'
WHERE CUSTOMER_ID LIKE 'FI-001' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='FI'
WHERE CUSTOMER_ID LIKE 'FT%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='RB'
WHERE CUSTOMER_ID LIKE 'RB%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='SME'
WHERE CUSTOMER_ID LIKE 'SME%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='MC'
WHERE CUSTOMER_ID LIKE 'MC%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='SOE'
WHERE CUSTOMER_ID LIKE 'SOE%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='QLTD'
WHERE CUSTOMER_ID LIKE 'QLTD%' AND VISION_SBU='NA'
/
UPDATE VISIONREAD.VW_TRANSCNT_FEED_STG_PL_202107 SET VISION_SBU='RB' WHERE VISION_SBU='NA'